[build]
  command = "npx expo export -p web"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--force"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[functions]
  node_bundler = "esbuild"
